"""Add building table

Revision ID: 4a8005983a2e
Revises: cf63d13b3376
Create Date: 2026-02-09 11:17:32.785281

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a8005983a2e'
down_revision: Union[str, Sequence[str], None] = 'cf63d13b3376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_index('idx_buildings_geom', 'buildings', ['geom'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.add_column('organizations', sa.Column('building_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'organizations', 'buildings', ['building_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'building_id')
    op.drop_index('idx_buildings_geom', table_name='buildings', postgresql_using='gist', if_exists=True)
    op.drop_table('buildings')
    # ### end Alembic commands ###
